### ISSUE TITLE
some files should be removed from the git repo

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#1]
https://github.com/GitHubLionel/wxMathPlot/blob/master/MathPlotConfig/MathPlotConfig.layout

https://github.com/GitHubLionel/wxMathPlot/blob/master/MathPlotConfig/MathPlotConfig.depend

Hi, the above files are C::B generated files, and they don't need to put in the git repo.

Thanks.

**Comment by GitHubLionel** [comment]
Ok done.

**Comment by asmwarrior** [comment]
Hi, @GitHubLionel , I just see your recent changes to the github repo, and I found that this file:

https://github.com/GitHubLionel/wxMathPlot/blob/master/MathPlotConfig/MathPlotConfig.layout

should be removed from the repo, because this `.layout` file is a user customized file to keep the window position and size.

Thanks.
