### ISSUE TITLE
constructor of the wxTextCtrl with validator generate wrong code

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#11]
![image](https://github.com/GitHubLionel/wxMathPlot/assets/561818/8e5406d6-80e8-410d-b053-f31979c07e82)

Loot at this image, it looks like it generate something like:

~~~~
edMarginTop = new wxTextCtrl(Panel1, ID_TEXTCTRL4, _T("50"), wxDefaultPosition, wxSize(40,-1), wxTE_RIGHT, wxIntegerValidator<unsigned int> (&int_top), _T("ID_TEXTCTRL4"));
~~~~

I guess that you have already remove the `_T` around the `50`, but what about the `_T("ID_TEXTCTRL4")`?

It looks like the window name(refer to this page:  [Textfield - what is wxTextCtrlNameStr?](https://stackoverflow.com/questions/2434891/textfield-what-is-wxtextctrlnamestr) and [wxWidgets: wxTextCtrl Class Reference](https://docs.wxwidgets.org/3.0/classwx_text_ctrl.html#a4f398e4800a904fdf225fabc366d7910) ) could be empty, but at least I think we don't need the `_T` here.

Oh, it looks like another issue for the wxSmith code generation.

**Comment by asmwarrior** [comment]
Maybe wxSmith is correct, it just give the wxTextCtrl a name (a string).

**Comment by GitHubLionel** [comment]
Yes, it's just a name for wxTextCtrl. wxSmith do that for all the widgets, I don't know how to avoid that.
