### ISSUE TITLE
using a more recent Code::Blocks to generate the MathPlotConfig.cpp

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#13]
Hi, when I open the wxSmith file, and I see my MathPlotConfig.cpp has some slightly difference with yours.

1, 
```
  BoxSizer8->Fit(Panel4);
  BoxSizer8->SetSizeHints(Panel4);
```
I see there are a lot of lines such as above were removed from the generated code.

2,

```
  edScaleMax = new wxTextCtrl(Panel3, ID_TEXTCTRL10, _("1"), wxDefaultPosition, wxSize(64,-1), wxTE_RIGHT, wxFloatingPointValidator<double> (2, &scale_max), _T("ID_TEXTCTRL10"));
	edScaleMax = new wxTextCtrl(Panel3, ID_TEXTCTRL10, _T("1"), wxDefaultPosition, wxSize(64,-1), wxTE_RIGHT, wxFloatingPointValidator<double> (2, &scale_max), _T("ID_TEXTCTRL10"));
```

You can see the `_()` is replaced by `_T()`, this is because: [wxSmith issue about the generation of _T() or _()](https://forums.codeblocks.org/index.php/topic,25392.msg173011.html#msg173011)

**Comment by GitHubLionel** [comment]
I use the official release 20.03.
I don't know why in 3 years there is no new release.

**Comment by asmwarrior** [comment]
We are preparing a new release this year.  But I think you can use a nightly build version of Code::Blocks, It's on the forum.

**Comment by GitHubLionel** [comment]
That's a good news.
If I can propose some enhancements, for example :
- the ability (with a checkbox in the IDE) to avoid the creation of the name of the widget (suppress all the long list of wxNewId())
- the creation of an array of string for the wxChoice widget
- the use of Bind in place of Connect
- an user code for i18n string. Default code is _("string") but if you have your own function, you wish could replace it by another thing (for example _myI18N("string")).

**Comment by asmwarrior** [comment]
I wrote a post in the C::B forum: [Some feature request about wxSmith on generating the code](https://forums.codeblocks.org/index.php/topic,25397.msg173048.html#msg173048)

**Comment by asmwarrior** [comment]
> the use of Bind in place of Connect

This feature is implemented, see the discussion in C::B forum. I have built C::B myself under Windows 64bit. If you like, I can share my built C::B binary. Or you can just wait for the next Windows C::B nightly build.

**Comment by GitHubLionel** [comment]
Not very friendly the C::B forum ! This is the message I got when I try to read the discussion :
> Sorry Guest, you are banned from using this forum!
> SPAM
> This ban is not set to expire.
I will wait for the nightly build or the next release.

**Comment by asmwarrior** [comment]
Oh, sorry about that, I have never see this, I will report to the C::B forum.

**Comment by asmwarrior** [comment]
> Oh, sorry about that, I have never see this, I will report to the C::B forum.

Oh, no, I see this first time:

> Sorry ollydbg, you are banned from using this forum!
> SPAM
> This ban is not set to expire.

I believe the forum is broken.

**Comment by asmwarrior** [comment]
The C::B forum is up now, see my reported ticket here: [Code::Blocks / Tickets / #1396 Our C::B forum is broken?](https://sourceforge.net/p/codeblocks/tickets/1396/)

**Comment by GitHubLionel** [comment]
Yep it's work now.
Two more requests (but I don't know if it is in the philosophy of C::B) :
- have a GitHub repository (I don't use SVN)
- have a makefile to build the project (I often use CMake)

**Comment by asmwarrior** [comment]
> Yep it's work now. Two more requests (but I don't know if it is in the philosophy of C::B) :
> 
>     * have a GitHub repository (I don't use SVN)

I also don't use SVN, but I use git-svn. If you need git, you can use Code::Blocks code mirror on github, it is here: 
[arnholm/codeblocks_sfmirror: Unofficial auto-updated GIT mirror of C::B repo in SourceForge. Does NOT accept patches nor pull requests.](https://github.com/arnholm/codeblocks_sfmirror)


> 
>     * have a makefile to build the project C::B IDE (I often use CMake)

makefile/configure method should work under Linux, but under Windows, I think currently the only way is using Code::Blocks to build Code::Blocks source code.

**Comment by GitHubLionel** [comment]
I try to build C::B with C::B. He build several files (a big codeblocks.dll 104 Mo) but I finally have this error :
`Execution of 'zip -jq9 devel32_64\share\CodeBlocks\manager_resources.zip sdk\resources\*.xrc'`

**Comment by asmwarrior** [comment]
> I try to build C::B with C::B. He build several files (a big codeblocks.dll 104 Mo) but I finally have this error : `Execution of 'zip -jq9 devel32_64\share\CodeBlocks\manager_resources.zip sdk\resources\*.xrc'`

I guess that you need a `zip.exe` in your `PATH` searching folders, so that those files can be zipped to a single file. This happens when you run the `update32_64.bat`.

This `bat` file just copy some files from the `devel32_64` folder to the `output32_64`, and will run `strip.exe` on the exe or dll files, so the final codeblocks.dll and exe files should be much smaller. I mean all the debug information will be removed.

**Comment by GitHubLionel** [comment]
> I guess that you need a `zip.exe` in your `PATH` searching folders, so that those files can be zipped to a single file. This happens when you run the `update32_64.bat`.

Yes that what I thought but I have nowhere `zip.exe`. Whitch `zip.exe` do you use ?

**Comment by asmwarrior** [comment]
See this wiki page of codeblocks: [4.3 ZIP](https://wiki.codeblocks.org/index.php/MinGW_installation#ZIP)

**Comment by asmwarrior** [comment]
![image](https://github.com/GitHubLionel/wxMathPlot/assets/561818/7330dec6-8d03-4bf7-b14f-c99bbe9e8b1a)

You need to check this option if you need the `Bind` function.

**Comment by GitHubLionel** [comment]
Ok, I succeeded :)
After the classical problem with wx/setup.h and library not found, compilation is done (just a problem at the end with `boost`, but without consequences over the final output).
Bind is ok but I have always the long list of wxNewId().
In the screenshot you provide, we see that we have choice for `Non-I18N strings`. Why not have a similar choice for `I18N` (the only choice is _()) ?

**Comment by asmwarrior** [comment]
> Ok, I succeeded :) After the classical problem with wx/setup.h and library not found, compilation is done (just a problem at the end with `boost`, but without consequences over the final output). 
Good work, I normally don't build the plugin which needs boost library. I just remove that plug in from the workspace.


> Bind is ok but I have always the long list of wxNewId(). In the screenshot you provide, we see that we have choice for `Non-I18N strings`. Why not have a similar choice for `I18N` (the only choice is _()) ?

I am not quite familiar with wxsmith code generation. Can you discuss on that cb forum thread?  What do you want if you don't like a list of wxNewID function call?

I think _() is the standard way for translation.

**Comment by GitHubLionel** [comment]
Now that I understand how to compile C::B, I will modify wxSmith to have what I want. In fact, it's quite easy.
So I will have my own version :)

**Comment by GitHubLionel** [comment]
I create a new thread for this : [https://github.com/GitHubLionel/wxMathPlot/issues/14](https://github.com/GitHubLionel/wxMathPlot/issues/14)
