### ISSUE TITLE
wxNullBrush will cause assert error message when open the MathPlotConfig dialog

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#16]
Hi, if I have some code: `xxx->SetBrush(wxNullBrush);` for a line, I will get an assert in the code:

~~~~
void MathPlotConfigDialog::UpdateSelectedSerie(void)
{
  CurrentSerie = (mpLayer*)m_plot->GetLayerPlot(ChoiceSeries->GetSelection());

  if (CurrentSerie)
  {
    CurrentChoice = ChoiceSeries;

    edSeriesName->SetValue(CurrentSerie->GetName());
    // Pen config
    bSeriesPenColor->SetBackgroundColour(CurrentSerie->GetPen().GetColour());
    cbSeriesPenWidth->SetSelection(CurrentSerie->GetPen().GetWidth() - 1);
    cbSeriesPenStyle->SetSelection(CurrentSerie->GetPen().GetStyle() - wxPENSTYLE_SOLID);
    // Brush config
    bSeriesBrushColor->SetBackgroundColour(CurrentSerie->GetBrush().GetColour());
    cbSeriesBrushStyle->SetSelection(BrushStyleToId(CurrentSerie->GetBrush().GetStyle()));
~~~~

You see in the last two lines, the `wxNullBrush` has NO colour and style information.

So, the wx will popup some alert message about this. Any ideas how to fix this? I think we have to check whether the brush is valid?

**Comment by asmwarrior** [comment]
OK, to workaround this issue, I can use `xxx->SetBrush(*wxTRANSPARENT_BRUSH);`.

**Comment by GitHubLionel** [comment]
Well, set `wxNullBrush` is not a good idea since we need a brush.
I directly put a test in `SetBrush` method of `mpLayer` to avoid this case.

**Comment by asmwarrior** [comment]
Thank for your fix!

I think this issue can be closed.
