### ISSUE TITLE
When you update the GUI related file in the repo, can you update the wxSmith file accordingly

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#2]
Hi, I see you have update some GUI related file, but it looks like the wxSmith file is not updated accordingly.

Can you also updating this `.wxs` file? Because I think the GUI file is generated from the wxSmith file.

BTW: I'm not sure, but why are you update the file by uploading the files to github, I think a normal git commit/push is much simple and better, and easy to track the changes.

Thanks.

**Comment by asmwarrior** [comment]
Hi, I think the correct and standard git client is: [Git for Windows](https://gitforwindows.org/). You can just use the git add/commit/push command through the command line or the `git gui` GUI tool.

I haven't used `GitHub GUI` before.

The file `.depend` is also not needed in the git repo, this file is generated by Code::Blocks for tracking the compiler dependency for each files.

There is another issue, I think the generated `exe/dll` binary files should be put in the `Release` section of the github page. (You can upload the zip file as the release) Those binaries are not suitable to put inside the git repo.

**Comment by GitHubLionel** [comment]
Hi,
I tried "[GitHub Desktop](https://desktop.github.com/)" and work fine (I would like a French translation, but it's ok).
The binary is just the sample exe if somebody want to quickly test. I don't know where is the Release section.
Regards,
Lionel

**Comment by asmwarrior** [comment]
> The binary is just the sample exe if somebody want to quickly test. I don't know where is the Release section. Regards, Lionel

Hi, you can look at this github document:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by GitHubLionel** [comment]
This is done.

**Comment by asmwarrior** [comment]
> This is done.

Thanks!

One more question, I see there are two `MathPlotConfig.cpp` files:

One is 

https://github.com/GitHubLionel/wxMathPlot/blob/master/MathPlotConfig/MathPlotConfig.cpp

Another file is:

https://github.com/GitHubLionel/wxMathPlot/blob/master/mathplot/MathPlotConfig.cpp

Does the two `MathPlotConfig.cpp` were all generated from the same wxSmith file (https://github.com/GitHubLionel/wxMathPlot/blob/master/MathPlotConfig/wxsmith/MathPlotConfigdialog.wxs) ?

Thanks.

**Comment by asmwarrior** [comment]
OK, thanks for the reply.

Do you mean that this is a wxSmith generation error? if that is true, I think we can change the wxSmith source code to generate the correct code.

**Comment by GitHubLionel** [comment]
Hi,

It is not an error but a warning like this one :
```cast between incompatible pointer to member types from 'void (MyFrame::*)(wxCommandEvent&)' to 'wxObjectEventFunction' {aka 'void (wxEvtHandler::*)(wxEvent&)'} [-Wcast-function-type]```
So to avoid this warning, I change the code.
Note that I use wxWidget 3.2.1. Maybe it was correct in an older version.

**Comment by asmwarrior** [comment]
> Hi,
> 
> It is not an error but a warning like this one : `cast between incompatible pointer to member types from 'void (MyFrame::*)(wxCommandEvent&)' to 'wxObjectEventFunction' {aka 'void (wxEvtHandler::*)(wxEvent&)'} [-Wcast-function-type]` So to avoid this warning, I change the code. Note that I use wxWidget 3.2.1. Maybe it was correct in an older version. Maybe, replace connect() by bind() will be a better solution.

Oh, it looks like I don't see this kind of warning in my Code::Blocks.

BTW, it looks like you are not using the latest Code::Blocks, so the wxSmith generated code are slightly different between mine and yours.
You can see this commit in my fork of your repo.

[newer wxSmith will automatically update the generated code by adding …](https://github.com/asmwarrior/wxMathPlot/commit/d3fd67d6da2e897721ec0b50ee46001accc17153)

The latest Code::Blocks can be downloaded from the nightly build forum: [Nightly builds](https://forums.codeblocks.org/index.php/board,20.0.html)
