### ISSUE TITLE
Demo asserts when trying to clear graph (DelAllPlot bug)

### ISSUE THREAD

**Issue by DRNadler** [GitHubLionel/wxMathPlot#23]
First graph draws great, but second uses DelAllPlot which asserts.
Windows 10, wxWidgets 3.2.5, just cloned this version of wxMathPlot.
Some details:
![wxPlot_Demo_asserts_clearing_graph_MathPlot_detail](https://github.com/user-attachments/assets/bc62c634-acc5-4830-81d8-01184f54b0bf)
![wxPlot_Demo_asserts_clearing_graph_STL_detail](https://github.com/user-attachments/assets/0c3f4cea-04ab-4015-9c25-85888fe1cf87)
![wxPlot_Demo_asserts_clearing_graph](https://github.com/user-attachments/assets/ffe4d780-8f43-432c-ab36-879b76fef5d7)

**Comment by DRNadler** [comment]
The bug: the iterator is invalidated by the `m_layers.erase(it);` in DelLayer... So the iterator increment operator fails in DelAllPlot (I am using the Visual Studio 2022 debug build, where the STL checks such stuff to avoid undefined behavior).

**Comment by GitHubLionel** [comment]
Hello
I don't have this issue with C::B and Eclipse but I don't have latest release of wxWidgets.
I try a correction with another approach who reinitialize the iterator after delete the layer.
Should be work !
Thanks for the Microsoft Visual Studio project. I merge it.
Lionel

**Comment by DRNadler** [comment]
Thanks for merging in my fixes, working without crashes now!
