### ISSUE TITLE
Scaling bug: Problem in Fit() or bounding box processing?

### ISSUE THREAD

**Issue by DRNadler** [GitHubLionel/wxMathPlot#30]
In demo program, click the following:
1. Draw sinus (OK)
2. Draw Sample (OK)
3. Draw sinus (now not properly scaled).

Or:
1. Draw Sample (OK)
2. Draw Barchart (not properly scaled)
3. Draw Barchart (now properly scaled)

Any idea what is going on?
Thanks!

**Comment by asmwarrior** [comment]
I can confirm you mentioned bugs. I'm not sure why.

BTW: I see you have made a lot of contributions to this library. Great job.

**Comment by GitHubLionel** [comment]
Yes and the problem come in the latest correction in delete all :(

**Comment by GitHubLionel** [comment]
I go back to my first correction using do ... while

**Comment by DRNadler** [comment]
Seems OK now, Thanks....
Sorry about all the iterator confusion...
