### ISSUE TITLE
How to obtain current view bounding-box in user coordinates?

### ISSUE THREAD

**Issue by DRNadler** [GitHubLionel/wxMathPlot#38]
After a zoom operation (use mouse to draw a zoom rectangle), I need to find the bounding box of the updated view, in my coordinates (not screen coordinates). In my mpFXY derivative it seems to be stored in `m_win->m_desired`, but that member is protected.

What's the best way to obtain the current view bounding box?

Thanks!

PS: GetBBox(&BB) returns the original complete bounds, not the smaller zoomed-in area

**Comment by GitHubLionel** [comment]
You have several GetDesired... flavor to have the m_desired values.
We can add a function like GetBoundingBox for m_desired ?

**Comment by DRNadler** [comment]
Pull request just added... Is it OK?

**Comment by GitHubLionel** [comment]
Ok, work no problem
