### ISSUE TITLE
Add custom choices in the wxChoice under wxSmith

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#4]
I use the latest C::B to open the project, and the wxSmith file.

After that I see that the re-generated cpp code has such changes in MathPlotConfig.cpp:

~~~~
-	cbCoord = new wxChoice(Panel1, ID_CHOICE11, wxDefaultPosition, wxDefaultSize, 10, cbCoord_choices, 0, wxDefaultValidator, _T("ID_CHOICE11"));
+	cbCoord = new wxChoice(Panel1, ID_CHOICE11, wxDefaultPosition, wxDefaultSize, 0, 0, 0, wxDefaultValidator, _T("ID_CHOICE11"));
~~~~

It looks like the wxSmith does not support user defined choices.

My guess is that you just manually edit the generated MathPlotConfig.cpp.

I would like to find a way to support such feature so that you do not need to manually edit the generated cpp file.

**Comment by asmwarrior** [comment]
To handle this, I have manually add those lines in the end of the constructor `MathPlotConfigDialog::MathPlotConfigDialog(wxWindow *parent, wxWindowID WXUNUSED(id))`:

~~~~
	// General panel's wxChoice
	cbCoord->Set(10, cbCoord_choices);
	cbCoordBrushStyle->Set(2, cbBrushStyle_choices);

	// Legend panel's wxChoice
	cbLegendPosition->Set(9, cbLegendPosition_choices);
	cbLegendStyle->Set(2, cbLegendStyle_choices);
	cbLegendDirection->Set(2, cbLegendDirection_choices);
	cbLegendBrushStyle->Set(2, cbBrushStyle_choices); // reused

	// Axis panel's wxChoice
	ChoiceAxis->Set(2, ChoiceAxis_choices);
	cbAxisPenWidth->Set(10, cbPenWidth_choices);
	cbAxisPenStyle->Set(5, cbPenStyle_choices);
	// cbAxisPosition->

	//Seriaes panel's wxChoice
	cbSeriesPenWidth->Set(10, cbPenWidth_choices);
	cbSeriesPenStyle->Set(5, cbPenStyle_choices);
	cbSeriesBrushStyle->Set(8, cbSeriesBrushStyle_choices);
	cbSeriesSymbolType->Set(7, cbSeriesSymbolType_choices);
~~~~

Can you try it?

Maybe, a better way is to do like this(using `sizeof`):

~~~~
cbCoord->Set(sizeof(cbCoord_choices), cbCoord_choices);
~~~~

**Comment by asmwarrior** [comment]
Oh, sorry, `sizeof` is wrong here, we should use `WXSIZEOF`, see here: [Length of wxString array? - wxWidgets Discussion Forum](https://forums.wxwidgets.org/viewtopic.php?t=17628)

**Comment by asmwarrior** [comment]
I have fixed this issue in my own forked branch here:

https://github.com/asmwarrior/wxMathPlot/commits/master

But please note that I'm using the wxWidgets library from msys2(installed by the `pacman` command), so I need to use a tool named `wx-config-msys2.exe` from [eranif/wx-config-msys2: wx-config tool for MSYS2 based installation of wxWidgets using the mingw64 repository](https://github.com/eranif/wx-config-msys2).

So, in my branch, the `.cbp` file is different from yours.

**Comment by GitHubLionel** [comment]
Hi
Yes I manually change the code generated by wxSmith (I use WinMerge to quickly redo change after wxSmith rebuild). I do this change because on Linux, the height of the choice is not good with the code of wxSmith. 
Note that I use C::B only to create the IHM and after I use Eclipse.
I introduce WXSMITH_CHOICE define to use your code, so the 2 configurations are possible.

**Comment by asmwarrior** [comment]
Hi, thanks for the fix.

I have another idea about the unified code:

I see the wxChoice has an option in the wxSmith setting dialog which user can add the item directly. 
I mean:

![image](https://user-images.githubusercontent.com/561818/230748895-f1264dcb-bf83-4111-80a2-ae202dd27d01.png)

In the above screen shot, If I add two lines in the "choice" property of the wxChoice in the wxSmith, I will generate two lines like:

~~~~
diff --git a/MathPlotConfig/MathPlotConfig.cpp b/MathPlotConfig/MathPlotConfig.cpp
index cb0d40e..b20efee 100644
--- a/MathPlotConfig/MathPlotConfig.cpp
+++ b/MathPlotConfig/MathPlotConfig.cpp
@@ -300,6 +300,8 @@ MathPlotConfigDialog::MathPlotConfigDialog(wxWindow *parent, wxWindowID WXUNUSED
 	StaticText23 = new wxStaticText(Panel1, ID_STATICTEXT23, _T("Style :"), wxDefaultPosition, wxDefaultSize, 0, _T("ID_STATICTEXT23"));
 	FlexGridSizer4->Add(StaticText23, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 5);
 	cbCoordBrushStyle = new wxChoice(Panel1, ID_CHOICE13, wxDefaultPosition, wxDefaultSize, 0, 0, 0, wxDefaultValidator, _T("ID_CHOICE13"));
+	cbCoordBrushStyle->Append(_T("Solid"));
+	cbCoordBrushStyle->Append(_T("Transparent"));
 	FlexGridSizer4->Add(cbCoordBrushStyle, 1, wxALL|wxEXPAND, 2);
 	StaticBoxSizer4->Add(FlexGridSizer4, 0, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
 	StaticBoxSizer3->Add(StaticBoxSizer4, 0, wxALL|wxALIGN_TOP, 5);
~~~~

I'm not sure, but this method can avoid making the manually code changes.

What do you think about it? Thanks.

**Comment by GitHubLionel** [comment]
Hi,
That's what I do at the beginning. But with this method, the height of the widget is not correctly handled under Linux (it's a GTK problem).

**Comment by asmwarrior** [comment]
> Hi, That's what I do at the beginning. But with this method, the height of the widget is not correctly handled under Linux (it's a GTK problem). 

I think you can post an issue on the wx's github site. So that it won't get forgotten.

> If wxSmith could create an array of string instead, that would be great (wxGlade do that). And it is a more efficient code.

I think wxSmith can do this, but I'm not sure I can handle it.
Maybe you can ask this feature request in the C::B forum.

For example, if a wxChoice is named `a`, and the choices could named `a_choices`.

**Comment by asmwarrior** [comment]
> I think I found a workaround for the choice. I use "Extra code" of wxSmith to populate the choices list. I update the git with this solution. I can not test on Linux because my Linux computer is out but normally, it should be work correctly.

This is really a good idea.  Luckily wxsmith has an extra code field to implement such feature.  I also don't have a Linux computer, but I think your fix is correct.  Thanks.

**Comment by asmwarrior** [comment]
I think this issue can be closed as implemented.
