### ISSUE TITLE
Some bars are not shown correctly

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#5]
See the image below, I think some bars are not shown correctly(they are missing). Because those bars are beyond the Y limit.

![image](https://user-images.githubusercontent.com/561818/230314577-1283ec43-550b-4458-8fd6-9990df2fcadc.png)

**Comment by GitHubLionel** [comment]
Hi
Yes I saw this behaviour and I will investigate how to correct this.
View bar is quite "experimental" (I do not use it). I just add it after have seeing the code of [Naiche](https://github.com/naiche/wxMathPlot) that I found very complicated.

**Comment by GitHubLionel** [comment]
Well it is corrected.
In fact, there was some old outdated code !

**Comment by asmwarrior** [comment]
Thanks, I see the fix now.

But I'm see other wx related assert messagebox when I try to change the line style to "bar", so I will debug the code to see whether it comes from my own code or not.

**Comment by asmwarrior** [comment]
Hi, with the latest git head version, I see the bars are shown correctly. And I don't see the assert messagebox now, so I think this issue is fixed, thanks.
