### ISSUE TITLE
duplicated lines in the comment

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#52]
https://github.com/GitHubLionel/wxMathPlot/blob/9f9bedee2c55bdd758cac306f3ed98d758bdc0e7/mathplot/mathplot.h#L6-L9

You see, there are duplicated lines in the comment.

**Comment by asmwarrior** [comment]
https://github.com/GitHubLionel/wxMathPlot/blob/9f9bedee2c55bdd758cac306f3ed98d758bdc0e7/mathplot/mathplot.h#L762C1-L766C52

There is a typo, should be `overridden`, you see the double `r`.

**Comment by GitHubLionel** [comment]
Ok corrected.

**Comment by asmwarrior** [comment]
> Ok corrected.

Oh, no, it should be "overridden", you lost one "d".

**Comment by GitHubLionel** [comment]
Arghh, ok corrected again :+1:

**Comment by asmwarrior** [comment]
I will close this issue, since the bug is fixed now, thanks.
