### ISSUE TITLE
mpInfoLegend::GetPointed returns wrong result

### ISSUE THREAD

**Issue by DRNadler** [GitHubLionel/wxMathPlot#59]
I've submitted a pull request documenting the problem, with suggested fix.

**Comment by GitHubLionel** [comment]
Yes `GetPointed` is not perfect but doesn't work so badly !

**Comment by GitHubLionel** [comment]
I don't like your "not acceptable" but it's fixed.

**Comment by DRNadler** [comment]
With acceptance of my pull request this is OK now (one DRY fix outstanding).
So you can close this issue...
