### ISSUE TITLE
Any idea to add the trackbox feature

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#6]
I think this project: [naiche/wxMathPlot: Fork of wxMathPlot based on MachMotionOpenSource/wxMathPlot, tracker and configurable mouse commands implemented.](https://github.com/naiche/wxMathPlot)

has a very nice feature named "trackbox", I guess it is a good idea to add this feature in your project, any ideas?

Thanks.

**Comment by GitHubLionel** [comment]
The position "cursor position" of the mouse coordinates is quite the same thing, no ?

**Comment by GitHubLionel** [comment]
:) lol
In the "General" page of the configuration and the "Mouse coordinates" box.

**Comment by asmwarrior** [comment]
> :) lol In the "General" page of the configuration and the "Mouse coordinates" box.

No, that is different. the trackbox shous the point coordinates in the plotted lines.

**Comment by GitHubLionel** [comment]
Ok, I see. 
I think it is not complicated. Just find the layer "close" to the mouse coordinates and get the coordinates of the layer.

**Comment by asmwarrior** [comment]
Yes, you are right. 
I think you should have an option to let the user select which layers should the coordinates show in trackbox.

**Comment by GitHubLionel** [comment]
Hi
It's done. I implement a very simple code (much more simply than naiche !). So I add a tractable property for series and a "Series coordinates" for the infocoords. 
Same time, I have made change to the configuration window. I also add "format" for Axis.
The only change that can break old version is the introduction of virtual DoPlot method. This method is the heart of the plot operation. The old Plot method just do some control and initialization before call DoPlot. So, if you have problem, just rename your Plot method to DoPlot and it will work.

**Comment by asmwarrior** [comment]
> Hi It's done. I implement a very simple code (much more simply than naiche !). So I add a tractable property for series and a "Series coordinates" for the infocoords. Same time, I have made change to the configuration window. I also add "format" for Axis. The only change that can break old version is the introduction of virtual DoPlot method. This method is the heart of the plot operation. The old Plot method just do some control and initialization before call DoPlot. So, if you have problem, just rename your Plot method to DoPlot and it will work.

Hi, thanks, I have just tested your github head code, the trackbox works great!
For the `DoPlot` related changes, I see you have such code:

~~~~
void mpLayer::Plot(wxDC &dc, mpWindow &w)
{
	if ((!m_visible) || m_busy)
		return;

	m_busy = true;
	DoBeforePlot();
	UpdateContext(dc);
	DoPlot(dc, w);
	m_busy = false;
}
~~~~
I understand the logic here.

For me, I have some extended(customized) class code in other cpp files, which derived from the `mpFXYVector`, such as:

~~~~
class WXDLLIMPEXP_MATHPLOT MyExtendedVector : public mpFXYVector
{
~~~~
I just changed the `Plot` to `DoPlot` in my extended class, and the code works OK.

**Comment by asmwarrior** [comment]
I think I would like to ask another feature request, when the mouse is near the curve(with the trackbox enabled), is it possible to have the tacked point highlighted. See the image below:

![image](https://user-images.githubusercontent.com/561818/231621774-cccf8440-a5e2-43ed-967a-f3e988baf0d0.png)

In this image screen shot, I have add an red arrow, I would like to highlight the point. In the naiche's implementation of trackbox, the box is shown on the serial lines. the left top of the box is moved when you move the mouse(see the image show in naiche's github page: https://github.com/naiche/wxMathPlot). But in your implementation, the trackbox is fixed on the window, in my screen shot, it is located in the bottom right corner.

Another issue is that when two serial lines are shown, when the mouse is near the line, the trackbox should shows which serial line is tracked.

Any ideas?

Thanks.

**Comment by GitHubLionel** [comment]
You can change the position "bottom right" to "Cursor position", so it will be like in Naiche picture.

**Comment by asmwarrior** [comment]
> You can change the position "bottom right" to "Cursor position", so it will be like in Naiche picture.

Oh, thanks, the "Cursor position" is vary nice option, I like it. It works quite well!

**Comment by GitHubLionel** [comment]
Great.
What I also can do, is to plot a small coloured square behind the y coordinates (like in legend). So it will be easy to identify the series pointed. I do that ?

**Comment by asmwarrior** [comment]
You mean add an icon behind the y coordinates? Like the image shot below (pointed by arrow?)

![image](https://user-images.githubusercontent.com/561818/231682361-e1d343b9-7f16-4cca-9fc7-3bfa6c602d2b.png)

I think it is OK.

**Comment by GitHubLionel** [comment]
Ok, I do that ;)

**Comment by GitHubLionel** [comment]
It's done :)

**Comment by asmwarrior** [comment]
> It's done :)

Thank.

I just test it, the icon is "before" the y coordinates, not "behind" it.

See image shot below:

![image](https://user-images.githubusercontent.com/561818/231711008-ce11fb28-4d96-429f-aaf6-ef9d70bac212.png)

**Comment by GitHubLionel** [comment]
Yes, english problem but it work ;)

**Comment by asmwarrior** [comment]
I think the recent two commit fix some crash. I have a derived class from mpFXY, and I don't set the `m_series_coord` field in the derived class. And I see a crash when the trackbox feature is enabled. I guess it is related to some uninitialized wxPen or wxBrush pointers issue, and I see your recent commit has changed it to reference and I don't see the crash here.

**Comment by GitHubLionel** [comment]
m_series_coord is not a field of mpFXY. It's a boolean to switch mouse/layer coordinates in mpInfoCoords.
The main purpose of the last commit was to homogenize the access of the objects (pen, brush, ...) in the getter/setter functions. I don't think that could break something and in any case, correction is easy.
I just add font for Legend.

**Comment by asmwarrior** [comment]
> m_series_coord is not a field of mpFXY. It's a boolean to switch mouse/layer coordinates in mpInfoCoords. The main purpose of the last commit was to homogenize the access of the objects (pen, brush, ...) in the getter/setter functions. I don't think that could break something and in any case, correction is easy. 

OK, thanks for the explanation, I will check them later.

> I just add font for Legend.
Good!
I also see you have change the layer drawing sequence, that's great, because the axis should be in the top of other graph.
