### ISSUE TITLE
Question: Can you post an example how to do real time plotting?

### ISSUE THREAD

**Issue by DanielMartensson** [GitHubLionel/wxMathPlot#68]
Nice library! I'm going to use this.

By the way! Can you show and example about how to do a real time plotting? Like a while loop that plots random numbers in real time.

**Comment by GitHubLionel** [comment]
Thanks :)
Suppose you have a mpFXYVector series and a Timer 1 s, then the onTimer event would be for example : 
```
void MyFrame::OnTimer(wxTimerEvent &WXUNUSED(event))
{
  static double x = 10;
  double y = (rand() * 10) / RAND_MAX;
  mpFXYVector* serie = (mpFXYVector*)m_plot->GetLayerPlot(0);
  if (serie->AddData(x, y, true))
    m_plot->Fit();  //  or UpdateAll()
  x += 0.2;
}`
