### ISSUE TITLE
If X axis is not shown, then the vertical grid lines are missing

### ISSUE THREAD

**Issue by asmwarrior** [GitHubLionel/wxMathPlot#7]
When I pan the graph, and the X axis moved out of the scene, then I see the vertical grid lines are disappeared.

While, if I pan the graph, and when the Y axis moved out of the scene, then the horizontal grid lines are disappeared.

I think this is a bug. Thanks.

**Comment by GitHubLionel** [comment]
Hi
It is not a bug, it is the normal behaviour when position of axis is "Center"  and axis is not visible (outside bound).

**Comment by asmwarrior** [comment]
> Hi It is not a bug, it is the normal behaviour when position of axis is "Center" and axis is not visible (outside bound).

Thanks.

I think it twice, the(you mentioned) logic is correct. It means when an axis is disappeared, the grid line has no coordinate information. I mean people has to look through the grid line, and see the position where the grid line and the axis get crossed, and see its coordinates.
